version: '2'

services:
   db:
     image: postgres:9.6.2
     volumes:
       - db_data:/var/lib/postgres
     restart: always
     environment:
       POSTGRES_USER: orbis
       POSTGRES_PASSWORD: orbis
       POSTGRES_DB: orbis

   memory-hole:
     depends_on:
       - db
     image: orbisnetwork/orbis-grcmanager:latest
     ports:
       - "8000:3000"
     restart: always
     environment:
       DATABASE_URL: jdbc:postgresql://db/orbis?user=orbis&password=orbis
volumes:
    db_data:
